stages:
 - build

build-dev:
 rules:
  - if: '$CI_COMMIT_BRANCH == "development"'
 image: registry.internal.st/dual-universe/dubuild:latest
 stage: build
 variables:
  GIT_SUBMODULE_STRATEGY: recursive
 script:
  - dotnet /app/DUBuild.dll build -s $CI_PROJECT_DIR -o $CI_PROJECT_DIR/output -m $CI_PROJECT_DIR/Main_*.lua -w false
 artifacts:
    paths:
      - $CI_PROJECT_DIR/output/*.json

build-prod:
 rules:
  - if: '$CI_COMMIT_BRANCH == "master"'
 image: registry.internal.st/dual-universe/dubuild:latest
 stage: build
 variables:
  GIT_SUBMODULE_STRATEGY: recursive
 script:
  - dotnet /app/DUBuild.dll build -s $CI_PROJECT_DIR -o $CI_PROJECT_DIR/output -m $CI_PROJECT_DIR/Main_*.lua
 artifacts:
    paths:
      - $CI_PROJECT_DIR/output/*.json