stages:
 - build
  
build:
 image: registry.internal.st/dual-universe/dubuild:latest
 stage: build
 variables:
  GIT_SUBMODULE_STRATEGY: recursive
 script:
  - dotnet /app/DUBuild.dll build -s $CI_PROJECT_DIR -o $CI_PROJECT_DIR/output -m $CI_PROJECT_DIR/Main_*.lua
 artifacts:
    paths:
      - $CI_PROJECT_DIR/output/*.json